### ISSUE TITLE
Optional line chart labels

### ISSUE THREAD

**Issue by brodysmith1** [stephenhutchings/shown#6]
Sure it can be messy with fluctuating or multiple lines, but it would be nice to give users the option to add value labels to line charts. I think a default position above the `shape`, and if necessary, the user can move points around using css.

I've got a working example on my forked shown repo, and can make a PR if you'd consider adding this in.

Otherwise if not, the MapOptions docs should be updated to indicate `label` isn't available for line charts.

**Comment by stephenhutchings** [comment]
This makes a lot of sense. I've added to your changes on this [branch](https://github.com/stephenhutchings/shown/tree/line-chart-labels).

On messiness, I think it makes sense to default to no labels for line charts, with the option to turn them on.

One question I have is the best DOM structure. Should labels be inserted alongside the symbols? There are a few advantages:
1. Each point could use a nested `<svg>` which controls the placement rather than duplicating across the shape and label.
2. User CSS could trigger a label to show when hovering over the associated symbol.

```css
.shown .point .label {
  opacity: 0;
  pointer-events: none;
  transition: opacity 300ms;
}

.shown .point:hover .label {
  opacity: 1;
}
```

I've also implemented an optional smart label placement strategy, where labels are shifted to minimise intersections with their own line. So instead of always placing them 1em above the shape, they are shifted 1em in whichever direction is furthest from the line tangent.

Another consideration is label colour. The default scheme uses a yellow that is too light for text, but I'm not sure if there is a simple solution without major changes.

Also, using `alignment-baseline` is much better than the `dy="-0.33em"`, so I am keen to switch to this model across all the charts. But "central" is probably a better choice than "middle". The latter is half the x-height, but the most common use case is numbers, so.

**Comment by brodysmith1** [comment]
Awesome Steve, thanks for integrating (and improving) the changes so quickly. Smart placement is a bonus.

Agree with all your decisions, including the DOM structure question.

Re color, I think it should match the stroke of the line. Are you planning to update Shown to use the oklch-smooth palette at some point? Maybe that's an opportunity to rethink the default colors. (Potentially adding different defaults for light/dark themes?)

The labels are off by default, so I wouldn't be too concerned about the yellow for now. I would assume (based on personal experience) that most users define a custom color scheme to suit their data anyway.
